site_name: My Docs
plugins:
  - search
  - macros
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences
theme:
  name: material
